#!/usr/bin/env python

import sys
import zlib
import hashlib

f = open(sys.argv[1], 'rb')
data = f.read()

# compute CRC32
crc = zlib.crc32(data) & 0xffffffffL

# compute SHA1
h = hashlib.sha1()
h.update(data)
sha1 = h.hexdigest()

# output defines
print "#define ULTIM809_MESS_CHECKSUMS CRC(%08x) SHA1(%s)" % (crc, sha1)

f.close()